from setuptools import setup, find_packages

setup(
    name="amazon-sentiment-analysis",
    version="1.0.0",
    description="Amazon Review Sentiment Analysis Model",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "torch>=1.12.0",
        "transformers>=4.21.0",
        "datasets>=2.4.0",
        "scikit-learn>=1.1.0",
        "pandas>=1.4.0",
        "numpy>=1.21.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.11.0",
        "tqdm>=4.64.0",
        "huggingface-hub>=0.8.0",
        "accelerate>=0.12.0",
        "fastapi>=0.78.0",
        "uvicorn>=0.18.0",
        "pydantic>=1.9.0",
        "python-multipart>=0.0.5",
        "gunicorn>=20.1.0",
        "python-dotenv>=0.20.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)